server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/arakh/blog-config/
          searchPaths: gateway, blog, finance, authentication, approval, reporting
          username: arakh
          password: R4h4s144j4

jasypt:
  encryptor:
    password: arkhyterima